### ISSUE TITLE
[enhancement] Condense Data into one sheet

### ISSUE THREAD

**Issue by FlygaM** [StareInTheAir/dldu-points#2]
The current way the google sheet is set up makes sense from a data separation POV, but isn't necessarily user friendly. The separation into different sheets makes it unnecessary hard to find and edit a specific value.

This issue could be resolved by condensing the data into a single sheet, which could look similar to this: [docs.google.com](https://docs.google.com/spreadsheets/d/1cBpKgh97VlBA2bCVurMB-eCaRKsSwn9EOvZWIPlaVhI/edit?usp=sharing)
It would additionally open up options for users to use googles filter function to only display bosses that are alive to make it easier towards the end of a run[^1].
This change would need to be addressed in [dldu-points/src/google-sheets.ts (currently Line 38)](https://github.com/StareInTheAir/dldu-points/blob/main/src/google-sheets.ts#L38)
```function googleDataToDlduData (googleData: GoogleSheetsDlduData): DlduData {
  const levels: DarkSoulsLevel[] = []
  // return if the Spreadsheet has no sheets. Shouldn't be possible but check anyway just to be sure.
  if (googleData.sheets.length = 0) {
	console.warn(`Ignoring empty Spreadsheet`)
	return {}
  }
  // since everything is compressed to one sheet, we just need the first one. Could alteratively check for name.
  const sheet = googleData.sheets[0]
  
  const levelName = ''
  const isFirstLevel = true // only true while working on the first level
  const bosses: DarkSoulsBoss[] = []
  const rowData = sheet.data[0]?.rowData
  const isFirstRow = true // only true on first row
  if (rowData != null) {
	for (const row of rowData) {
          // ignore first row since it's only header information
          if (isFirstRow) {
            isFirstRow = false
            continue
          }
	  // check if current row has Area information
	  if (row.values.length >= 5 &&
		  row.values[4].formattedValue === 'Area') {
		// push previous level when next Area is reached starting with the 2nd level
		if (!isFirstLevel) {
		  if (levelName.length > 0 && bosses.length > 0) {
		    levels.push({ name: levelName, bosses })
		  } else {
		    console.warn(`Ignoring empty level ${levelName}`)
		  }
		} else {
		  isFirstLevel = false
		}
		// set new levelName and reset bosses array
		levelName = row.values[0].formattedValue.trim()
		bosses = []
		// continue so we don't trigger the 'ignoring boss [...]' warning
		continue
	  } else if (row.values.length >= 3 &&
		  row.values[0].formattedValue != null &&
		  row.values[1].formattedValue != null &&
		  row.values[2].formattedValue != null) {
		const name = row.values[0].formattedValue.trim()
		const points = parseInt(row.values[1].formattedValue.trim())
		const beaten = row.values[2].formattedValue === 'beaten'
		if (name.length > 0 && !isNaN(points)) {
		  bosses.push({ name, points, beaten })
		  continue
		}
	  }
	  console.warn(`Ignoring boss ${JSON.stringify(row)} in level ${levelName}`)
	}
  }
  // push last level
  if (levelName.length > 0 && bosses.length > 0) {
    levels.push({ name: levelName, bosses })
  } else {
    console.warn(`Ignoring empty level ${levelName}`)
  }

  return { levels }
}
```

The google sheet includes some additional QOL proposals.

- Tick boxes to make it easier to mark beaten (mini)bosses[^2]
- Options sheet to change the point values for (mini)bosses, so they don't have to be edited manually
- Calculated status value for levels (open || completed)
- Pinned tick box (not yet used) in regards to the Issue #1 which could be used to pin a specific level (ideally the current level the participant is working on) so it's always shown in the overlay

[^1]: e.g. filter by condition `=OR(AND($E2="Area",$C2="open"),AND($D2=FALSE,$D2<>""))`
[^2]: which means their data (true || false) could also be used directly instead of checking for the string 'beaten' `const beaten = row.values[2].formattedValue === 'beaten'` vs. `const beaten = row.values[3].formattedValue`

**Comment by StareInTheAir** [comment]
Thanks for your suggestions. I considered this before, but didn't follow through.

I created another proposal based in your proposal: https://docs.google.com/spreadsheets/d/1_Tn673N1v82LwOvFGkrqM5unOFDev61IUvkAHs8Z7V0

I simplified your sheet. I want the sheet to be as easy as possible, so that extending it is also straight forward. Using formulas is over most peoples heads, so my version is not using them. To add an level or boss, users should in the best case just need to fill in text, not needing to add rows or copy formulas.

Pinning a level would indeed help solve issue #1

**Comment by StareInTheAir** [comment]
I further refined my new template and the implementation is also done. It's available on branch `one-sheet`. Here is [the diff to main](https://github.com/StareInTheAir/dldu-points/compare/one-sheet) if you are interested. If there are no further comments, I will merge to main soon and deploy the new version. It will be breaking change, because you will need to use the new template

**Comment by StareInTheAir** [comment]
Version 2.0.0 is now on main and also deployed. The main change is the new sheet structure with only one sheet.
